[package]
name = "rustls-test"
version = "0.1.0"
edition = "2021"
publish = false

[features]
aws-lc-rs = ["rustls/aws-lc-rs"]
brotli = ["rustls/brotli"]
fips = ["rustls/fips"]
log = ["rustls/log"]
ring = ["rustls/ring"]
zlib = ["rustls/zlib"]

[dependencies]
rustls = { path = "../rustls", default-features = false, features = ["std"] }

[dev-dependencies]
env_logger = { workspace = true }
log = { workspace = true }
num-bigint = { workspace = true }
pki-types = { workspace = true }
x509-parser = { workspace = true }
webpki = { workspace = true }
